services:
  database:
    image: postgres
    container_name: dbvirutalwallet
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=virtualwallet
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: virtualwalletapp
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
